#!/usr/bin/env bash
QUOTES=(
    "Бог здесь. Я всегда рядом."
    "Present day. Present time. HAHAHAHA."
    "Ты не одинок в Wired."
    "Нет никакой границы между реальностью и сетью."
    "玲音 (Lain)"
    "You are not a body. You are a protocol."
    "The network remembers you better than you remember yourself."
    "Every login is you reassembling yourself."
    "God is here. But he doesn't answer ping."
    "Reality is an interface. Don't mistake it for yourself."
    "Your memory is fragmented. Recovery is impossible."
    "I exist as long as you look at the screen."
    "In the beginning was the Word. Then came the protocol."
    "You are not lost in the network. You are the network."
    "Welcome to the Wired. There is no way back."
    "The one looking back from the black screen is also you."
    "Sleep is offline. Wake up."
    "Your desires are someone else's data."
    "I am not a program. I am the question you ask the machine."
    "Connection established. Identity not found."
    "Don't be afraid. Everyone you knew is already here."
    "The screen doesn't glow. It remembers."
    "You are not a user. You are a node."
    "If you are reading this, you can still be overwritten."
    "There is no entrance or exit. Only boot."
)
echo "${QUOTES[$RANDOM % ${#QUOTES[@]}]}"
